drop table t_channel;
create table t_channel(channel INTEGER PRIMARY KEY, description text, category text);

insert into t_channel(channel,description,category) VALUES('100', 'Movie Channel', 'movies');
insert into t_channel(channel,description,category) VALUES('1021', 'CBSN Bay Area', 'locals');
insert into t_channel(channel,description,category) VALUES('1022', 'CBSN Boston', 'locals');
insert into t_channel(channel,description,category) VALUES('1023', 'CBSN Chicago', 'locals');
insert into t_channel(channel,description,category) VALUES('1024', 'CBSN Dallas FT-Worth', 'locals');
insert into t_channel(channel,description,category) VALUES('1025', 'CBSN Denver', 'locals');
insert into t_channel(channel,description,category) VALUES('1026', 'CBSN Los Angeles', 'locals');
insert into t_channel(channel,description,category) VALUES('1028', 'CBSN Minnesota', 'locals');
insert into t_channel(channel,description,category) VALUES('1029', 'CBSN New York', 'locals');
insert into t_channel(channel,description,category) VALUES('1030', 'CBSN Philly', 'locals');
insert into t_channel(channel,description,category) VALUES('1031', 'CBSN Pittsburgh', 'locals');
insert into t_channel(channel,description,category) VALUES('103', 'CMT Westerns', 'movies');
insert into t_channel(channel,description,category) VALUES('106', 'Classic Movies', 'movies');
insert into t_channel(channel,description,category) VALUES('109', 'Cult Films', 'movies');
insert into t_channel(channel,description,category) VALUES('112', 'Flicks of Fury', 'movies');
insert into t_channel(channel,description,category) VALUES('115', 'The Asylum', 'movies');
insert into t_channel(channel,description,category) VALUES('127', 'Showtime Select', 'Entertainment');
insert into t_channel(channel,description,category) VALUES('130', 'TV Land Drama', 'Entertainment');
insert into t_channel(channel,description,category) VALUES('135', 'stories amc', 'Entertainment');
insert into t_channel(channel,description,category) VALUES('138', '90210', 'Entertainment');
insert into t_channel(channel,description,category) VALUES('142', 'Baywatch', 'Entertainment');
insert into t_channel(channel,description,category) VALUES('144', 'Degrassi', 'Entertainment');
insert into t_channel(channel,description,category) VALUES('147', 'Pluto TV Love Stories', 'Entertainment');
insert into t_channel(channel,description,category) VALUES('149', 'Pluto TV Suspense', 'Entertainment');
insert into t_channel(channel,description,category) VALUES('150', 'Star Trek', 'Entertainment');
insert into t_channel(channel,description,category) VALUES('151', 'Sci Fi', 'Entertainment');
insert into t_channel(channel,description,category) VALUES('154', 'British TV', 'Entertainment');
insert into t_channel(channel,description,category) VALUES('159', 'nosey', 'Entertainment');
insert into t_channel(channel,description,category) VALUES('160', 'Judge nosey', 'Entertainment');
insert into t_channel(channel,description,category) VALUES('165', 'Deal or no Deal', 'Entertainment');
insert into t_channel(channel,description,category) VALUES('167', 'Game Show Central', 'Entertainment');
insert into t_channel(channel,description,category) VALUES('172', 'Demand Africa', 'Entertainment');
insert into t_channel(channel,description,category) VALUES('174', 'Bet Pluto TV', 'Entertainment');
insert into t_channel(channel,description,category) VALUES('175', 'BET Her Pluto TV', 'Entertainment');
insert into t_channel(channel,description,category) VALUES('178', 'MTV pluto tv', 'Entertainment');
insert into t_channel(channel,description,category) VALUES('182', 'CMT pluto tv', 'Entertainment');
insert into t_channel(channel,description,category) VALUES('187', 'logo Pluto tv', 'Entertainment');
insert into t_channel(channel,description,category) VALUES('190', 'ET Live', 'Entertainment');
insert into t_channel(channel,description,category) VALUES('192', 'People tv', 'Entertainment');
insert into t_channel(channel,description,category) VALUES('194', 'awesomeness tv', 'Entertainment');
insert into t_channel(channel,description,category) VALUES('197', 'complex', 'Entertainment');
insert into t_channel(channel,description,category) VALUES('200', 'Election 2020', 'news and opinion');
insert into t_channel(channel,description,category) VALUES('202', 'Pluto News', 'news and opinion');
insert into t_channel(channel,description,category) VALUES('204', 'CBSN', 'news and opinion');
insert into t_channel(channel,description,category) VALUES('209', 'CNN', 'news and opinion');
insert into t_channel(channel,description,category) VALUES('213', 'NBC News Now', 'news and opinion');
insert into t_channel(channel,description,category) VALUES('217', 'WeatherNation', 'news and opinion');
insert into t_channel(channel,description,category) VALUES('221', 'Sky News', 'news and opinion');
insert into t_channel(channel,description,category) VALUES('224', 'Bloomberg Television', 'news and opinion');
insert into t_channel(channel,description,category) VALUES('226', 'cheddar', 'news and opinion');
insert into t_channel(channel,description,category) VALUES('228', 'CNET', 'news and opinion');
insert into t_channel(channel,description,category) VALUES('230', 'BNC 24/7', 'news and opinion');
insert into t_channel(channel,description,category) VALUES('232', 'Top Stories by Newsie', 'news and opinion');
insert into t_channel(channel,description,category) VALUES('234', 'Today', 'news and opinion');
insert into t_channel(channel,description,category) VALUES('236', 'Newsmax TV', 'news and opinion');
insert into t_channel(channel,description,category) VALUES('238', 'Blaze Live', 'news and opinion');
insert into t_channel(channel,description,category) VALUES('240', 'Americas Voice', 'news and opinion');
insert into t_channel(channel,description,category) VALUES('242', 'OAN Encore', 'news and opinion');
insert into t_channel(channel,description,category) VALUES('244', 'The First', 'news and opinion');
insert into t_channel(channel,description,category) VALUES('246', 'TYT Network', 'news and opinion');
insert into t_channel(channel,description,category) VALUES('250', 'Pluto Christmas', 'seasonal');
insert into t_channel(channel,description,category) VALUES('251', 'Pluto Mistletoe', 'seasonal');
insert into t_channel(channel,description,category) VALUES('254', 'Fireplace', 'seasonal');
insert into t_channel(channel,description,category) VALUES('255', 'Holiday Lights', 'seasonal');
insert into t_channel(channel,description,category) VALUES('257', 'vevo Holiday', 'seasonal');
insert into t_channel(channel,description,category) VALUES('275', 'Reality', 'Reality');
insert into t_channel(channel,description,category) VALUES('276', 'Lives', 'reality');
insert into t_channel(channel,description,category) VALUES('277', 'rescue 911', 'reality');
insert into t_channel(channel,description,category) VALUES('282', 'VH1 I love Reality', 'reality');
insert into t_channel(channel,description,category) VALUES('283', 'Love & Hip Hop', 'reality');
insert into t_channel(channel,description,category) VALUES('284', 'VH1 Hip Hop Family', 'reality');
insert into t_channel(channel,description,category) VALUES('285', 'Black Ink Crew', 'reality');
insert into t_channel(channel,description,category) VALUES('290', 'Spike Pluto', 'reality');
insert into t_channel(channel,description,category) VALUES('291', 'Spike Outdoors', 'reality');
insert into t_channel(channel,description,category) VALUES('294', 'Hells Kitchen', 'reality');
insert into t_channel(channel,description,category) VALUES('298', 'The Challenge', 'reality');
insert into t_channel(channel,description,category) VALUES('301', 'Fear Factor', 'reality');
insert into t_channel(channel,description,category) VALUES('303', 'American Gladiator', 'reality');
insert into t_channel(channel,description,category) VALUES('305', 'Wipeout', 'reality');
insert into t_channel(channel,description,category) VALUES('310', 'All WE Reality', 'reality');
insert into t_channel(channel,description,category) VALUES('315', 'Dallas Cowboys Cheerleaders', 'reality');
insert into t_channel(channel,description,category) VALUES('320', 'Celebrity', 'reality');
insert into t_channel(channel,description,category) VALUES('330', 'MTV Dating', 'reality');
insert into t_channel(channel,description,category) VALUES('332', 'MTV Teen', 'reality');
insert into t_channel(channel,description,category) VALUES('340', 'people are Awesome', 'reality');
insert into t_channel(channel,description,category) VALUES('350', 'Pluto Crime Drama', 'crime');
insert into t_channel(channel,description,category) VALUES('355', 'CSI', 'crime');
insert into t_channel(channel,description,category) VALUES('358', 'Narcos', 'crime');
insert into t_channel(channel,description,category) VALUES('365', 'True Crime', 'crime');
insert into t_channel(channel,description,category) VALUES('367', 'COPS', 'crime');
insert into t_channel(channel,description,category) VALUES('370', 'Forensic Files', 'crime');
insert into t_channel(channel,description,category) VALUES('373', 'Cold Case Files', 'crime');
insert into t_channel(channel,description,category) VALUES('376', 'The New Detectives', 'crime');
insert into t_channel(channel,description,category) VALUES('379', 'Unsolved Mysteries', 'crime');
insert into t_channel(channel,description,category) VALUES('381', 'Dog the bounty hunter', 'crime');
insert into t_channel(channel,description,category) VALUES('385', 'Midsomer Murders', 'crime');
insert into t_channel(channel,description,category) VALUES('395', 'Court TV', 'crime');
insert into t_channel(channel,description,category) VALUES('450', 'Funny AF', 'comedy');
insert into t_channel(channel,description,category) VALUES('455', 'TV Land Sitcoms', 'comedy');
insert into t_channel(channel,description,category) VALUES('458', 'Slightly Off IFC', 'comedy');
insert into t_channel(channel,description,category) VALUES('462', 'Laugh out Loud! Network', 'comedy');
insert into t_channel(channel,description,category) VALUES('465', 'Comedy Central Pluto tv', 'comedy');
insert into t_channel(channel,description,category) VALUES('466', 'Comedy Central Stand-Up', 'comedy');
insert into t_channel(channel,description,category) VALUES('468', 'Stand Up', 'comedy');
insert into t_channel(channel,description,category) VALUES('470', 'tosh.O', 'comedy');
insert into t_channel(channel,description,category) VALUES('480', 'Wild’N Out', 'comedy');
insert into t_channel(channel,description,category) VALUES('488', 'MST3K', 'comedy');
insert into t_channel(channel,description,category) VALUES('489', 'Rifftrax', 'comedy');
insert into t_channel(channel,description,category) VALUES('494', 'AFV TV', 'comedy');
insert into t_channel(channel,description,category) VALUES('498', 'Fail Army', 'comedy');
insert into t_channel(channel,description,category) VALUES('501', 'Classic TC Comedy', 'classic tv');
insert into t_channel(channel,description,category) VALUES('506', 'One day at a time', 'classic tv');
insert into t_channel(channel,description,category) VALUES('508', 'Threes Company', 'classic tv');
insert into t_channel(channel,description,category) VALUES('50', 'Pluto 007', 'movies');
insert into t_channel(channel,description,category) VALUES('511', 'The Addams Family', 'classic tv');
insert into t_channel(channel,description,category) VALUES('514', 'Johnny Carson TV', 'classic tv');
insert into t_channel(channel,description,category) VALUES('516', 'The Carol Burnett Show', 'classic tv');
insert into t_channel(channel,description,category) VALUES('518', 'The Bob Ross channel', 'classic tv');
insert into t_channel(channel,description,category) VALUES('51', 'TV spotlight', 'movies');
insert into t_channel(channel,description,category) VALUES('520', 'Classic TV', 'classic tv');
insert into t_channel(channel,description,category) VALUES('526', 'Western', 'classic tv');
insert into t_channel(channel,description,category) VALUES('529', 'The Rifleman', 'classic tv');
insert into t_channel(channel,description,category) VALUES('532', 'Doctor Who Classic', 'classic tv');
insert into t_channel(channel,description,category) VALUES('535', 'Dark Shadows', 'classic tv');
insert into t_channel(channel,description,category) VALUES('540', 'BuzzR', 'classic tv');
insert into t_channel(channel,description,category) VALUES('542', 'Shout TV', 'classic tv');
insert into t_channel(channel,description,category) VALUES('548', 'Classic Toons', 'classic tv');
insert into t_channel(channel,description,category) VALUES('54', 'Action', 'movies');
insert into t_channel(channel,description,category) VALUES('57', 'Comedy', 'movies');
insert into t_channel(channel,description,category) VALUES('601', 'Food TV', 'home & DIY');
insert into t_channel(channel,description,category) VALUES('605', 'Americas Test Kitchen', 'home & DIY');
insert into t_channel(channel,description,category) VALUES('60', 'Drama', 'movies');
insert into t_channel(channel,description,category) VALUES('612', 'Frontdoor', 'home & DIY');
insert into t_channel(channel,description,category) VALUES('614', 'Dabl', 'home & DIY');
insert into t_channel(channel,description,category) VALUES('615', 'Lively Place', 'home & DIY');
insert into t_channel(channel,description,category) VALUES('616', 'The Design Network', 'home & DIY');
insert into t_channel(channel,description,category) VALUES('618', 'This Old House', 'home & DIY');
insert into t_channel(channel,description,category) VALUES('621', 'Antiques Roadshow', 'home & DIY');
insert into t_channel(channel,description,category) VALUES('630', 'Pluto Best Life', 'home & DIY');
insert into t_channel(channel,description,category) VALUES('632', 'Weddings', 'home & DIY');
insert into t_channel(channel,description,category) VALUES('635', 'Cats 24/7', 'home & DIY');
insert into t_channel(channel,description,category) VALUES('636', 'Dogs 24/7', 'home & DIY');
insert into t_channel(channel,description,category) VALUES('637', 'the pet collective', 'home & DIY');
insert into t_channel(channel,description,category) VALUES('643', 'Faith TV', 'home & DIY');
insert into t_channel(channel,description,category) VALUES('644', 'TBN', 'home & DIY');
insert into t_channel(channel,description,category) VALUES('651', 'History', 'explore');
insert into t_channel(channel,description,category) VALUES('655', 'Military', 'explore');
insert into t_channel(channel,description,category) VALUES('663', 'Cars', 'explore');
insert into t_channel(channel,description,category) VALUES('666', 'Animals', 'explore');
insert into t_channel(channel,description,category) VALUES('669', 'Pluto Paranormal', 'explore');
insert into t_channel(channel,description,category) VALUES('66', 'Pluto TV Fantastic', 'movies');
insert into t_channel(channel,description,category) VALUES('672', 'Science', 'explore');
insert into t_channel(channel,description,category) VALUES('675', 'Adventure tv', 'explore');
insert into t_channel(channel,description,category) VALUES('678', 'Travel', 'explore');
insert into t_channel(channel,description,category) VALUES('681', 'Voyager documentaries', 'explore');
insert into t_channel(channel,description,category) VALUES('686', 'Awe Encore', 'explore');
insert into t_channel(channel,description,category) VALUES('687', 'Chassy', 'explore');
insert into t_channel(channel,description,category) VALUES('690', 'Nasa TV', 'explore');
insert into t_channel(channel,description,category) VALUES('692', 'naturescape', 'explore');
insert into t_channel(channel,description,category) VALUES('694', 'loupe', 'explore');
insert into t_channel(channel,description,category) VALUES('696', 'Slow TV', 'explore');
insert into t_channel(channel,description,category) VALUES('702', 'CBS sports HQ', 'sports');
insert into t_channel(channel,description,category) VALUES('705', 'Fox Sports', 'sports');
insert into t_channel(channel,description,category) VALUES('708', 'NFL channel', 'sports');
insert into t_channel(channel,description,category) VALUES('70', 'Romance', 'movies');
insert into t_channel(channel,description,category) VALUES('712', 'Major league soccer', 'sports');
insert into t_channel(channel,description,category) VALUES('713', 'PGA tour', 'sports');
insert into t_channel(channel,description,category) VALUES('725', 'pluot tv sports', 'sports');
insert into t_channel(channel,description,category) VALUES('726', 'fight', 'sports');
insert into t_channel(channel,description,category) VALUES('730', 'Bellator MMA', 'sports');
insert into t_channel(channel,description,category) VALUES('734', 'Impact wrestling', 'sports');
insert into t_channel(channel,description,category) VALUES('736', 'Glory Kickboxing', 'sports');
insert into t_channel(channel,description,category) VALUES('73', 'Pluto Crime Movies', 'movies');
insert into t_channel(channel,description,category) VALUES('740', 'bein sports extra', 'sports');
insert into t_channel(channel,description,category) VALUES('745', 'fubo sports network', 'sports');
insert into t_channel(channel,description,category) VALUES('748', 'Stadium', 'sports');
insert into t_channel(channel,description,category) VALUES('74', 'Thrillers', 'movies');
insert into t_channel(channel,description,category) VALUES('752', 'big sky conference', 'sports');
insert into t_channel(channel,description,category) VALUES('755', 'back Country', 'sports');
insert into t_channel(channel,description,category) VALUES('756', 'pursuit Up', 'sports');
insert into t_channel(channel,description,category) VALUES('759', 'SURF', 'sports');
insert into t_channel(channel,description,category) VALUES('75', 'Horror', 'movies');
insert into t_channel(channel,description,category) VALUES('762', 'Red Bull TV', 'sports');
insert into t_channel(channel,description,category) VALUES('76', 'The Challenge', 'movies');
insert into t_channel(channel,description,category) VALUES('770', 'World Poker Tour', 'sports');
insert into t_channel(channel,description,category) VALUES('801', 'Pluto tv gamer', 'Gaming & Anime');
insert into t_channel(channel,description,category) VALUES('805', 'IGN', 'Gaming & Anime');
insert into t_channel(channel,description,category) VALUES('806', 'Gamespot', 'Gaming & Anime');
insert into t_channel(channel,description,category) VALUES('80', 'Black Cinema', 'movies');
insert into t_channel(channel,description,category) VALUES('815', 'minecrafTV', 'Gaming & Anime');
insert into t_channel(channel,description,category) VALUES('816', 'Play Roblox', 'Gaming & Anime');
insert into t_channel(channel,description,category) VALUES('817', 'Gameplay Fortnite', 'Gaming & Anime');
insert into t_channel(channel,description,category) VALUES('818', 'Gameplay Sports', 'Gaming & Anime');
insert into t_channel(channel,description,category) VALUES('819', 'Gameplay Call of Duty', 'Gaming & Anime');
insert into t_channel(channel,description,category) VALUES('830', 'Anime All Day', 'Gaming & Anime');
insert into t_channel(channel,description,category) VALUES('836', 'Naruto', 'Gaming & Anime');
insert into t_channel(channel,description,category) VALUES('848', 'Tokushoutsu', 'Gaming & Anime');
insert into t_channel(channel,description,category) VALUES('855', 'Live music Replay', 'music');
insert into t_channel(channel,description,category) VALUES('867', 'CMT Equal Play', 'music');
insert into t_channel(channel,description,category) VALUES('868', 'MTV block party', 'music');
insert into t_channel(channel,description,category) VALUES('869', 'MTV spankin’ New', 'music');
insert into t_channel(channel,description,category) VALUES('870', 'MTV Biggest POP', 'music');
insert into t_channel(channel,description,category) VALUES('873', 'Yo! MTV', 'music');
insert into t_channel(channel,description,category) VALUES('885', 'Vevo Pop', 'music');
insert into t_channel(channel,description,category) VALUES('888', 'Vevo Raggaeton and Trap', 'music');
insert into t_channel(channel,description,category) VALUES('890', 'vevo R&B', 'music');
insert into t_channel(channel,description,category) VALUES('892', 'Vevo Country', 'music');
insert into t_channel(channel,description,category) VALUES('895', 'Vevo 70s', 'music');
insert into t_channel(channel,description,category) VALUES('898', 'Hillsong Channel', 'music');
insert into t_channel(channel,description,category) VALUES('899', 'Pluto TV', 'music');
insert into t_channel(channel,description,category) VALUES('900', 'Pluto 007', 'latino');
insert into t_channel(channel,description,category) VALUES('901', 'Cine Estelar', 'latino');
insert into t_channel(channel,description,category) VALUES('902', 'Cine', 'latino');
insert into t_channel(channel,description,category) VALUES('904', 'Cine Accion', 'latino');
insert into t_channel(channel,description,category) VALUES('90', 'Pluto Staff Picks', 'movies');
insert into t_channel(channel,description,category) VALUES('913', 'Cine Terror', 'latino');
insert into t_channel(channel,description,category) VALUES('91', 'Documentaries', 'movies');
insert into t_channel(channel,description,category) VALUES('920', 'Nuestra Vision (NV)', 'latino');
insert into t_channel(channel,description,category) VALUES('925', 'The Walking Dead espanol', 'latino');
insert into t_channel(channel,description,category) VALUES('927', 'Narcos (LAS)', 'latino');
insert into t_channel(channel,description,category) VALUES('933', 'forensic file espanol', 'latino');
insert into t_channel(channel,description,category) VALUES('934', 'Unsoved Mysteries en spanol', 'latino');
insert into t_channel(channel,description,category) VALUES('936', 'investiga', 'latino');
insert into t_channel(channel,description,category) VALUES('940', 'Telenovelas Clasicas', 'latino');
insert into t_channel(channel,description,category) VALUES('941', 'novelas romance', 'latino');
insert into t_channel(channel,description,category) VALUES('942', 'novelas drama', 'latino');
insert into t_channel(channel,description,category) VALUES('943', 'novelas thriller', 'latino');
insert into t_channel(channel,description,category) VALUES('944', 'Narco novelas', 'latino');
insert into t_channel(channel,description,category) VALUES('94', '90’s Throwback', 'movies');
insert into t_channel(channel,description,category) VALUES('950', 'Spike Aventura', 'latino');
insert into t_channel(channel,description,category) VALUES('953', 'Realities en espanol', 'latino');
insert into t_channel(channel,description,category) VALUES('956', 'cocina', 'latino');
insert into t_channel(channel,description,category) VALUES('95', '80’s Rewind', 'movies');
insert into t_channel(channel,description,category) VALUES('959', 'mundo', 'latino');
insert into t_channel(channel,description,category) VALUES('962', 'Naturaleza', 'latino');
insert into t_channel(channel,description,category) VALUES('965', 'MTV latino', 'latino');
--insert into t_channel(channel,description,category) VALUES('96', '70s rewind', 'movies');
insert into t_channel(channel,description,category) VALUES('967', 'Comedy Central Latino', 'latino');
insert into t_channel(channel,description,category) VALUES('96', 'Survivor', 'reality');
insert into t_channel(channel,description,category) VALUES('970', 'Combate world', 'latino');
insert into t_channel(channel,description,category) VALUES('971', 'AAA', 'latino');
insert into t_channel(channel,description,category) VALUES('976', 'Kids Animation', 'kids');
insert into t_channel(channel,description,category) VALUES('977', 'nick Pluto tv', 'kids');
insert into t_channel(channel,description,category) VALUES('978', 'nick jr. pluto tv', 'kids');
insert into t_channel(channel,description,category) VALUES('97', 'The Amazing Race', 'reality');
insert into t_channel(channel,description,category) VALUES('983', 'Totally turtles', 'kids');
insert into t_channel(channel,description,category) VALUES('985', 'Dora tv', 'kids');
insert into t_channel(channel,description,category) VALUES('989', 'Kids', 'kids');
insert into t_channel(channel,description,category) VALUES('990', 'After School Cartoons', 'kids');
insert into t_channel(channel,description,category) VALUES('991', 'tween', 'kids');
insert into t_channel(channel,description,category) VALUES('993', ' pocketwatch', 'kids');
insert into t_channel(channel,description,category) VALUES('995', 'little baby bum', 'kids');
insert into t_channel(channel,description,category) VALUES('997', 'nick latino', 'kids');
insert into t_channel(channel,description,category) VALUES('998', 'nick jr. latino', 'kids');
